import = ["./themes/rose-pine-dawn.toml"]
[font]
  size = 18
  [font.normal]
    family = "FantasqueSansM Nerd Font Mono"
    # family = "JetBrainsMono NF"
[window]
  padding = { x = 5, y = 5 }
  dimensions = { columns = 120, lines = 40  }
  opacity= 0.95
  decorations = "Buttonless"

[cursor]
  unfocused_hollow = true
  style = {shape ="Beam",blinking = "On"}

[env]
  TERM = "xterm-256color"

[scrolling]
  history = 5000 

[[keyboard.bindings]]
  key = "F12"
  action = "ToggleFullscreen"


