import = ["~/workspace/dotfiles/alacritty/themes/catppuccin-mocha.toml"]
live_config_reload = true 

[font]
size = 16
normal = {family = "GeistMono Nerd Font",  style = "Regular"}
bold = {family = "GeistMono Nerd Font",  style = "Bold"}
italic = {family = "GeistMono Nerd Font",  style = "Italic"}

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 120, lines = 40 }
opacity = 1 
decorations = "Buttonless"                 #  "Full" | "None" | "Transparent" | "Buttonless"
blur = true
startup_mode = "Maximized" # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"

[cursor]
unfocused_hollow = true
style = { shape = "Block", blinking = "On" } # shape = "Block" | "Underline" | "Beam" 

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000


[[keyboard.bindings]]
key = "F12"
action = "ToggleFullscreen"
