import = ["~/workspace/dotfiles/alacritty/themes/gruvbox_material.toml"]
[font]
  size = 17 
  [font.normal]
    family = "GeistMono NF"
[window]
  padding = { x = 10, y = 10 }
  dimensions = { columns = 120, lines = 40  }
  opacity= 1
  decorations = "None" #  "Full" | "None" | "Transparent" | "Buttonless"
[cursor]
  unfocused_hollow = true
  style = {shape ="Underline",blinking = "On"} # shape = "Block" | "Underline" | "Beam" 

[env]
  TERM = "xterm-256color"

[scrolling]
  history = 10000 

[[keyboard.bindings]]
  key = "F12"
  action = "ToggleFullscreen"


