#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 1
yabai -m config window_shadow off
# add 0 padding to the top and 50 padding to bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:0:10

yabai -m config window_border                on 
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff9ece6a

yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alacritty Popup$" sticky=on layer=above manage=off

yabai -m rule --add app="^Skype$" sticky=on layer=above manage=off
yabai -m rule --add app="^Zalo$" sticky=on layer=above manage=off
yabai -m rule --add app="^Slack$" sticky=on layer=above manage=off
yabai -m rule --add app="^Telegram$" sticky=on layer=above manage=off
yabai -m rule --add app="^Discord$" sticky=on layer=above manage=off
yabai -m rule --add app="^zoom.us$" manage=off

yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Font Book$" manage=off


yabai -m rule --add app="^Docker Desktop$" layer=above manage=off
yabai -m rule --add app="^MongoDB Compass$" layer=above manage=off
yabai -m rule --add app="^Notion$" layer=above manage=off
yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on
yabai -m rule --add app="^WebStorm$" manage=off
yabai -m rule --add app="^Code$" manage=off
yabai -m rule --add app="^Figma$" manage=off
yabai -m rule --add app="^Postman$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off

yabai -m signal --add event=window_destroyed action="bash $HOME/dotfiles/yabai/scripts/window_focus_on_destroy.sh"

echo "yabai configuration loaded.."
