export ZSH="$HOME/.oh-my-zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# theme
ZSH_THEME="robbyrussell"

plugins=(
  git
  docker
  golang
  rust
  yarn
)

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# workspace
export WORKSPACE="$HOME/workspace"
# development
export DEVELOPMENT="$HOME/development"
# dotfiles
export DOTFILES="$WORKSPACE/dotfiles"

# go path
export GOPATH="$DEVELOPMENT/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$DEVELOPMENT/go/bin"

# java
export JAVA_HOME="/opt/homebrew/opt/openjdk"
# export PATH="$PATH:$JAVA_HOME/bin"

# composer
export PATH="$PATH:$HOME/.composer/vendor/bin"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

if [[ -t 0 ]]; then
  source $DOTFILES/zsh/greeting.zsh
  zsh_greeting
fi

# export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@16/lib/pkgconfig"
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"

export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

[ -f ~/.shell_eval ] && source ~/.shell_eval

[ -f ~/.aliases_zsh ] && source $HOME/.aliases_zsh

# Load Angular CLI autocompletion.
source <(ng completion script)


# pnpm
export PNPM_HOME="/Users/lehongphong/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
