#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias reload='source ~/.zshrc'

alias gsync="git checkout master && git fetch upstream && git rebase upstream/master && git push"

function set_work_git_config() {
    local repo_path="$(git rev-parse --show-toplevel 2>/dev/null)"

    if [ -n "$repo_path" ]; then
        cd "$repo_path"
        git config user.name "phonglenus"
        git config user.email "hongphongle115@gmail.com"
        echo "Đã thiết lập thông tin người dùng cho repo workspace."
    else
        echo "Không phải là một thư mục Git hoặc repo workspace không được tìm thấy."
    fi
}

alias setworkgitconfig="set_work_git_config"

# . /opt/homebrew/etc/profile.d/z.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=247"

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# workspace
export WORKSPACE="$HOME/workspace"

# dotfiles
export DOTFILES="$HOME/dotfiles"

# go path
export GOPATH="$WORKSPACE/go"
export PATH="$PATH:$HOME/workspace/go/bin"

# flutter
export PATH="$PATH:$HOME/development/flutter/bin"

# java
export JAVA_HOME="/opt/homebrew/opt/openjdk"
export PATH="$PATH:$JAVA_HOME/bin"

# rust
export PATH="$PATH:$HOME/.cargo/bin"

# composer
export PATH="$PATH:$HOME/.composer/vendor/bin"

# rvm
export PATH="$PATH:$HOME/.rvm/bin"


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Load Angular CLI autocompletion.
source <(ng completion script)

if [[ -t 0 ]]; then
  source $DOTFILES/zsh/greeting.zsh
  zsh_greeting
fi

# starship
eval "$(starship init zsh)"


