#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

ZSH_DISABLE_COMPFIX="true"

# https://spaceship-prompt.sh
# ZSH_THEME="spaceship"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"
function set_win_title() {
        echo -ne "\033]0; $(basename "$PWD") \007"
}

precmd_functions+=(set_win_title)

# Automatically load a node version in the current working directory.
NVM_AUTOLOAD=1

# Disable the highlighting of pasted text
zle_highlight=('paste:none')

# Spaceship customization
SPACESHIP_PROMPT_ADD_NEWLINE=false
# Prompt character to be shown before any command
SPACESHIP_CHAR_SYMBOL="  "
# Prefix before Git section
SPACESHIP_GIT_PREFIX="on branch  "
# Prefix before Git branch subsection
SPACESHIP_GIT_BRANCH_PREFIX=""
# Prefix before package version section
SPACESHIP_PACKAGE_PREFIX="version 爐"
# Character to be shown before package version
SPACESHIP_PACKAGE_SYMBOL=""
# Prefix before Node.js section
SPACESHIP_NODE_PREFIX="with  "
# Character to be shown before Node.js version
SPACESHIP_NODE_SYMBOL=""
# Show current active Conda configuration or not
SPACESHIP_CONDA_SHOW="false"
# Show current active gcloud configuration or not
SPACESHIP_GCLOUD_SHOW="false"
# Show Kubernetes section
SPACESHIP_KUBECTL_SHOW="true"
# Prefix before Kubernetes section
SPACESHIP_KUBECTL_PREFIX="environment   "
# Character to be shown before Kubernetes subsection
SPACESHIP_KUBECTL_SYMBOL=""
# Show Kubernetes version subsection
SPACESHIP_KUBECTL_VERSION_SHOW="false"
# Suffix after Kubectl context section
SPACESHIP_KUBECONTEXT_SUFFIX=""

# Customize to your needs...
alias reload='source ~/.zshrc'

alias gsync="git checkout master && git fetch upstream && git rebase upstream/master && git push"

function set_work_git_config() {
    local repo_path="$(git rev-parse --show-toplevel 2>/dev/null)"

    if [ -n "$repo_path" ]; then
        cd "$repo_path"
        git config user.name "unrealphong"
        git config user.email "hongphongle115@gmail.com"
        
        echo "Git user configured for the project."

    else
        echo "Could not find Git workspace or directory repo."
    fi
}

alias gitconfig="set_work_git_config"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=247"

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# [[ -z $TMUX ]] || conda deactivate; conda activate base

# workspace
export WORKSPACE="$HOME/workspace"
# development
export DEVELOPMENT="$HOME/development"
# dotfiles
export DOTFILES="$WORKSPACE/dotfiles"


# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

# go path
export GOPATH="$DEVELOPMENT/go"
export PATH="$PATH:$DEVELOPMENT/go/bin"

# java
export JAVA_HOME="/opt/homebrew/opt/openjdk"
export PATH="$PATH:$JAVA_HOME/bin"

# composer
# export PATH="$PATH:$HOME/.composer/vendor/bin"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Load Angular CLI autocompletion.
source <(ng completion script)

if [[ -t 0 ]]; then
  source $DOTFILES/zsh/greeting.zsh
  zsh_greeting
fi

# export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@16/lib/pkgconfig"
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"

export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

[ -f ~/.shell_eval ] && source ~/.shell_eval

# Enable prompt themes
[ -f ~/.zshrc.theme ] && source ~/.zshrc.theme
# Fix ls colors

